/*
 * usb_lib_flags.h
 *
 *  Created on: 16 apr. 2025
 *      Author: Ludo
 */

#ifndef __USB_LIB_FLAGS_H__
#define __USB_LIB_FLAGS_H__

#include "usb_configuration_sdr_fox.h"
#include "usb_hs_device.h"

/*** USB library compilation flags ***/

#define USB_LIB_HW_INTERFACE_ERROR_BASE_LAST                        USB_HS_DEVICE_ERROR_BASE_LAST

#define USBD_CONTROL_INTERFACE_INDEX                                USB_INTERFACE_INDEX_CONTROL
#define USBD_CONTROL_INTERFACE_STRING_DESCRIPTOR_INDEX              USB_STRING_DESCRIPTOR_INDEX_INTERFACE_CONTROL

#define USBD_CDC
#define USBD_UAC

#ifdef USBD_CDC

#define USBD_CDC_COMM_INTERFACE_INDEX                               USB_INTERFACE_INDEX_CDC_COMM
#define USBD_CDC_COMM_INTERFACE_STRING_DESCRIPTOR_INDEX             USB_STRING_DESCRIPTOR_INDEX_INTERFACE_CDC_COMM
#define USBD_CDC_COMM_ENDPOINT_NUMBER                               1
#define USBD_CDC_COMM_PACKET_SIZE_BYTES                             16

#define USBD_CDC_DATA_INTERFACE_INDEX                               USB_INTERFACE_INDEX_CDC_DATA
#define USBD_CDC_DATA_INTERFACE_STRING_DESCRIPTOR_INDEX             USB_STRING_DESCRIPTOR_INDEX_INTERFACE_CDC_DATA
#define USBD_CDC_DATA_ENDPOINT_NUMBER                               2
#define USBD_CDC_DATA_PACKET_SIZE_BYTES                             512

#endif /*  USBD_CDC */

#ifdef USBD_UAC

#define USBD_UAC_INTERFACE_ASSOCIATION_STRING_DESCRIPTOR_INDEX      USB_STRING_DESCRIPTOR_INDEX_INTERFACE_UAC_INTERFACE_ASSOCIATION

#define USBD_UAC_CONTROL_INTERFACE_INDEX                            USB_INTERFACE_INDEX_UAC_CONTROL
#define USBD_UAC_CONTROL_INTERFACE_STRING_DESCRIPTOR_INDEX          USB_STRING_DESCRIPTOR_INDEX_INTERFACE_UAC_CONTROL
#define USBD_UAC_CONTROL_ENDPOINT_NUMBER                            3
#define USBD_UAC_CONTROL_PACKET_SIZE_BYTES                          64

#define USBD_UAC_STREAM_PLAY_INTERFACE_INDEX                        USB_INTERFACE_INDEX_UAC_STREAM_PLAY
#define USBD_UAC_STREAM_PLAY_INTERFACE_STRING_DESCRIPTOR_INDEX      USB_STRING_DESCRIPTOR_INDEX_INTERFACE_UAC_STREAM_PLAY
#define USBD_UAC_STREAM_PLAY_ENDPOINT_NUMBER                        4
#define USBD_UAC_STREAM_PLAY_PACKET_SIZE_BYTES                      512

#define USBD_UAC_STREAM_RECORD_INTERFACE_INDEX                      USB_INTERFACE_INDEX_UAC_STREAM_RECORD
#define USBD_UAC_STREAM_RECORD_INTERFACE_STRING_DESCRIPTOR_INDEX    USB_STRING_DESCRIPTOR_INDEX_INTERFACE_UAC_STREAM_RECORD
#define USBD_UAC_STREAM_RECORD_ENDPOINT_NUMBER                      5
#define USBD_UAC_STREAM_RECORD_PACKET_SIZE_BYTES                    512

#endif /* USBD_UAC */

#endif /* __USB_LIB_FLAGS_H__ */
